-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 09:13:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `main` ENUM("Academico", "Administrativo") NOT NULL,
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  `type` ENUM("facultad", "programa", "departamento") NOT NULL,
  `procesoCalidad` TINYINT NULL,
  `Dependencia_idDependencia` INT NULL,
  PRIMARY KEY (`idDependencia`),
  INDEX `fk_Dependencia_Dependencia1_idx` (`Dependencia_idDependencia` ASC) ,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) ,
  UNIQUE INDEX `idDependencia_UNIQUE` (`idDependencia` ASC) ,
  CONSTRAINT `fk_Dependencia_Dependencia1`
    FOREIGN KEY (`Dependencia_idDependencia`)
    REFERENCES `mydb`.`Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autoevaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autoevaluacion` (
  `idAutoevaluacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_auto` DATE NULL,
  `fecha_reno` DATE NULL,
  `Dependencia_idDependencia` INT NOT NULL,
  PRIMARY KEY (`idAutoevaluacion`),
  INDEX `fk_Autoevaluacion_Dependencia1_idx` (`Dependencia_idDependencia` ASC),
  CONSTRAINT `fk_Autoevaluacion_Dependencia1`
    FOREIGN KEY (`Dependencia_idDependencia`)
    REFERENCES `mydb`.`Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vigencia_Programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vigencia_Programa` (
  `idVigencia_Programa` INT NOT NULL AUTO_INCREMENT,
  `tiempoVigencia` DATE NULL,
  `numeroResolucion` VARCHAR(45) NULL,
  `fechaResolucion` DATE NULL,
  `numeroMEN` VARCHAR(45) NULL,
  `type` ENUM("Acreditacion", "Registro_Calificado") NULL,
  `Dependencia_idDependencia` INT NOT NULL,
  PRIMARY KEY (`idVigencia_Programa`),
  INDEX `fk_Vigencia_Programa_Dependencia1_idx` (`Dependencia_idDependencia` ASC) ,
  CONSTRAINT `fk_Vigencia_Programa_Dependencia1`
    FOREIGN KEY (`Dependencia_idDependencia`)
    REFERENCES `mydb`.`Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
