-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 06:13:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dependencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `codigo` ENUM("facultad", "programa","departamento") NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  `type` ENUM("Academico", "Administrativo") NOT NULL,
  PRIMARY KEY (`idDependencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Facultad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Facultad` (
  `idFacultad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Dependencia_idDependencia` INT NOT NULL,
  PRIMARY KEY (`idFacultad`),
  INDEX `fk_Facultad_Dependencia_idx` (`Dependencia_idDependencia` ASC) ,
  CONSTRAINT `fk_Facultad_Dependencia`
    FOREIGN KEY (`Dependencia_idDependencia`)
    REFERENCES `mydb`.`Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Facultad_idFacultad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamento`, `Facultad_idFacultad`),
  INDEX `fk_Departamento_Facultad1_idx` (`Facultad_idFacultad` ASC) ,
  CONSTRAINT `fk_Departamento_Facultad1`
    FOREIGN KEY (`Facultad_idFacultad`)
    REFERENCES `mydb`.`Facultad` (`idFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Programa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Programa` (
  `idPrograma` INT NOT NULL AUTO_INCREMENT,
  `Facultad_idFacultad` INT NOT NULL,
  `procesoCalidad` TINYINT NULL,
  PRIMARY KEY (`idPrograma`, `Facultad_idFacultad`),
  INDEX `fk_Programa_Facultad1_idx` (`Facultad_idFacultad` ASC) ,
  CONSTRAINT `fk_Programa_Facultad1`
    FOREIGN KEY (`Facultad_idFacultad`)
    REFERENCES `mydb`.`Facultad` (`idFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autoevaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Autoevaluacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Autoevaluacion` (
  `idAutoevaluacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_auto` DATE NULL,
  `fecha_reno` DATE NULL,
  `Dependencia_idDependencia` INT NOT NULL,
  `Programa_idPrograma` INT NOT NULL,
  PRIMARY KEY (`idAutoevaluacion`),
  INDEX `fk_Autoevaluacion_Dependencia1_idx` (`Dependencia_idDependencia` ASC) ,
  INDEX `fk_Autoevaluacion_Programa1_idx` (`Programa_idPrograma` ASC) ,
  CONSTRAINT `fk_Autoevaluacion_Dependencia1`
    FOREIGN KEY (`Dependencia_idDependencia`)
    REFERENCES `mydb`.`Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autoevaluacion_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `mydb`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vigencia_Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vigencia_Programa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vigencia_Programa` (
  `idVigencia_Programa` INT NOT NULL AUTO_INCREMENT,
  `Programa_idPrograma` INT NOT NULL,
  `tiempoVigencia` DATE NULL,
  `numeroResolucion` VARCHAR(45) NULL,
  `fechaResolucion` DATE NULL,
  `numeroMEN` VARCHAR(45) NULL,
  `type` ENUM("Acreditacion", "Registro_Calificado") NULL,
  PRIMARY KEY (`idVigencia_Programa`),
  INDEX `fk_Vigencia_Programa_Programa1_idx` (`Programa_idPrograma` ASC) ,
  CONSTRAINT `fk_Vigencia_Programa_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `mydb`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
